import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/NavBar";
import Providers from "./Providers";

import { Noto_Sans_Tagalog } from "@next/font/google";

const roboto = Noto_Sans_Tagalog({
	subsets: ["latin"],
	weight: "400",
});

export const metadata: Metadata = {
	title: "GenieBucks",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${roboto.className}  antialiased`}>
				<Providers>
					<div className="h-screen w-screen text-ebony-100 bg-pearl-700 dark:bg-night-200 dark:text-old_lace transition duration-500">
						<div className=" w-full sm:w-[calc(80%)] lg:w-[calc(60%)] h-full mx-auto">
							<Navbar />
							{children}
						</div>
					</div>
				</Providers>
			</body>
		</html>
	);
}
