import type { Metadata } from "next";
import "@/app/globals.css";
import Providers from "@/app/Providers";

export const metadata: Metadata = {
	title: "GenieBucks",
	description: "Generated by create next app",
};

export default function MainLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="h-screen w-screen overflow-hidden">
				<Providers>
					<div className="h-screen w-screen text-[#080a21] dark:text-[#ebecf9] bg-[#f0f2f5] dark:bg-[#080a21] transition duration-500">
						<div className="w-full px-4 sm:w-[80%] sm:px-0 lg:w-[60%] h-full mx-auto flex flex-col">
							{children}
						</div>
					</div>
				</Providers>
			</body>
		</html>
	);
}
